version: '3.7'

services:
  nginx:
    environment:
      DOMAIN_URL: ${BRIDGE_URL}
      NODE_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      NODE_DOCKER_NAME: node
      NODE_PORT: 5000
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5

  node:
    environment:
      NODE_ENV: production
