version: '3.7'

networks:
  default:

volumes:
  redis:
  letsencrypt:

services:
  nginx:
    image: ${NGINX_IMAGE}
    deploy:
      mode: global
    # This port format is needed to get real ip address of the client
    # This completely defeats the purpose of Docker swarm and routing with load balancing
    # so are instead handling the load balancing with the nginx proxy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - letsencrypt:/etc/letsencrypt

  redis:
    image: 'redis:5-alpine'
    volumes:
      - redis:/data

  ${APP_NAME}0:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
