version: "3.7"

volumes:
  grafana:
  prometheus:

networks:
  default:

services:
  nginx:
    image: ${NGINX_IMAGE}
    environment:
      SUBDOMAINS: "grafana:3000"
    depends_on:
      - grafana

  exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri
      - http://nginx:8080/nginx_status
    ports:
      - "8000:9113"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
