version: "3.7"

volumes:
  grafana:
  prometheus:

networks:
  default:

services:
  nginx:
    image: ${NGINX_IMAGE}
    environment:
      SUBDOMAINS: "grafana:3000"
    depends_on:
      - grafana
    volumes:
      - ./nginx/exporter.conf:/etc/nginx/servers/exporter.conf

  exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri
      - http://nginx:8080/stub_status

  node_exporter:
    image: quay.io/prometheus/node-exporter 
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus
