version: '3.7'

services:
  redis:
    ports:
      - "6379:6379"
  node0:
    ports:
      - "5001:5001"
    volumes:
      - ../build:/root/build
  nginx:
    environment:
      CONTAINER_NAME: node
      APP_QTY: 1
    depends_on:
      - node0

