version: '3.7'

services:
  nginx:
    environment:
      DOMAIN_URL: ${BRIDGE_URL}
      NODE_ENV: production
      EMAIL: ${CERTBOT_EMAIL}
      NODE_DOCKER_NAME: node
      NODE_PORT: 5000
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node
  node:
    environment:
      NODE_ENV: production

  node1:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node2:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node3:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node4:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
  node5:
    image: ${WALLET_IMAGE}
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379/0
